// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Id        int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Author    *Message_Person            `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Text      string                     `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	StartTime *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=startTime" json:"startTime,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetAuthor() *Message_Person {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

type Message_Person struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Message_Person) Reset()                    { *m = Message_Person{} }
func (m *Message_Person) String() string            { return proto.CompactTextString(m) }
func (*Message_Person) ProtoMessage()               {}
func (*Message_Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Message_Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message_Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*Message_Person)(nil), "message.Message.Person")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0xc1, 0x6a, 0x84, 0x30,
	0x10, 0x86, 0x89, 0xb5, 0x8a, 0x53, 0xda, 0x43, 0x2e, 0x0d, 0x5e, 0x2a, 0x3d, 0x79, 0x28, 0x11,
	0xda, 0x4b, 0x5f, 0x62, 0x61, 0x09, 0xbe, 0x40, 0xc4, 0x59, 0x37, 0xb0, 0x31, 0x92, 0x8c, 0xb0,
	0x4f, 0xb8, 0xcf, 0xb5, 0x90, 0x28, 0x7b, 0xd8, 0xdb, 0x3f, 0xc3, 0x37, 0xff, 0x7c, 0xf0, 0x6e,
	0x31, 0x04, 0x3d, 0xa1, 0x5c, 0xbc, 0x23, 0xc7, 0xcb, 0x6d, 0xac, 0xbf, 0x26, 0xe7, 0xa6, 0x0b,
	0x76, 0x71, 0x3d, 0xac, 0xa7, 0x8e, 0x8c, 0xc5, 0x40, 0xda, 0x2e, 0x89, 0xfc, 0xbe, 0x31, 0x28,
	0x0f, 0x09, 0xe6, 0x1f, 0x90, 0x99, 0x51, 0xb0, 0x86, 0xb5, 0xaf, 0x2a, 0x33, 0x23, 0xef, 0xa0,
	0xd0, 0x2b, 0x9d, 0x9d, 0x17, 0x59, 0xc3, 0xda, 0xb7, 0xdf, 0x4f, 0xb9, 0x7f, 0xd9, 0x2e, 0xe4,
	0x11, 0x7d, 0x70, 0xb3, 0xda, 0x30, 0xce, 0x21, 0x27, 0xbc, 0x92, 0x78, 0x69, 0x58, 0x5b, 0xa9,
	0x98, 0xf9, 0x3f, 0x54, 0x81, 0xb4, 0xa7, 0xde, 0x58, 0x14, 0x79, 0xec, 0xa9, 0x65, 0xb2, 0x92,
	0xbb, 0x95, 0xec, 0x77, 0x2b, 0xf5, 0x80, 0xeb, 0x1f, 0x28, 0x52, 0xff, 0x93, 0x18, 0x87, 0x7c,
	0xd6, 0x16, 0xa3, 0x56, 0xa5, 0x62, 0x1e, 0x8a, 0x58, 0xf6, 0x77, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xf4, 0x0d, 0x53, 0x5d, 0x0a, 0x01, 0x00, 0x00,
}
